### ISSUE TITLE
Autocraft not working...Error in Console

### ISSUE THREAD

**Issue by Chris6ix** [ChestsPlusPlus/ChestsPlusPlus#77]
I just tried Chest++ on my clean 1.18.2 Paper (#283) Test Server as I'm quite interested in the autocraft feature for my Server...the thing is that is just doesn't work at all...

When I set it up, and it tries to start crafting, it doesn't work and just spams this Error into the console:

[ChestsPlusPlus] Task #222 for ChestsPlusPlus v2.6 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_17_R1/CraftWorld
        at com.jamesdpeters.minecraft.chests.v1_17_R1.Crafting.craft(Crafting.java:27) ~[ChestsPlusPlus-2.6-Release.jar:?]
        at com.jamesdpeters.minecraft.chests.crafting.Crafting.craft(Crafting.java:40) ~[ChestsPlusPlus-2.6-Release.jar:?]
        at com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder.craftItem(VirtualCraftingHolder.java:413) ~[ChestsPlusPlus-2.6-Release.jar:?]
        at com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder.craftItem(VirtualCraftingHolder.java:263) ~[ChestsPlusPlus-2.6-Release.jar:?]
        at com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder$CraftItems.run(VirtualCraftingHolder.java:226) ~[ChestsPlusPlus-2.6-Release.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-283]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_17_R1.CraftWorld
        ... 13 more

**Comment by ceze88** [comment]
Hi! Try the latest beta. You can find it in here in the releases page. Don't worry about the beta, it seems to be really stable!

**Comment by Chris6ix** [comment]
Alright, will try that one :)
If it fixes the issue, then I will close it

**Comment by BoxWithoutATop** [comment]
I am having this same issue. Do you also use any of the following plugins? Perhaps this is an incompatibility issue. As far as I'm aware a solution hasn't been found, were you able to resolve this Chris6ix?

**Comment by Chris6ix** [comment]
> I am having this same issue. Do you also use any of the following plugins? Perhaps this is an incompatibility issue. As far as I'm aware a solution hasn't been found, were you able to resolve this Chris6ix?

Hey, I didn't try again because the plugin is missing a lot of features that I really need...so i "abandoned" the idea for now until these things get added (#78 and #80)

But as "ceze88" already said above, you can try the latest beta build
So it seems that it has nothing to do with other plugins (That you didn't even list?) but just that the main release (v2.6) isn't compatible with 1.18.2, and it was only fixed in the beta...
So a solution seems to have been found...
Please read all comments before replying ;)

Didn't even know this was still open...so I'm closing it because it's no longer relevant as it's apparently a known issue that has been fixed :)
