### ISSUE TITLE
Cant create party

### ISSUE THREAD

**Issue by MrArron** [ChestsPlusPlus/ChestsPlusPlus#81]
When players click the anvil in the party menu it does nothing and the console spits out this error

[09:01:59 INFO]: MrArron issued server command: /cl party
[09:02:01 ERROR]: Could not pass event InventoryClickEvent to ChestsPlusPlus v2.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2462) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.util.thread.IAsyncTaskHandler.bo(SourceFile:116) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1145) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1051) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
	at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[?:?]
	at com.jamesdpeters.minecraft.chests.menus.TextInputUI.getInput(TextInputUI.java:16) ~[?:?]
	at com.jamesdpeters.minecraft.chests.menus.PartyMenu.create(PartyMenu.java:139) ~[?:?]
	at com.jamesdpeters.minecraft.chests.menus.PartyMenu.lambda$updateIcons$1(PartyMenu.java:71) ~[?:?]
	at com.jamesdpeters.minecraft.chests.ClickableItem.run(ClickableItem.java:135) ~[?:?]
	at com.jamesdpeters.minecraft.chests.InventoryManager$InvListener.lambda$onInventoryClick$2(InventoryManager.java:174) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at com.jamesdpeters.minecraft.chests.InventoryManager$InvListener.onInventoryClick(InventoryManager.java:174) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 20 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: AnvilGUI does not support server version "1_18_R2" [in thread "Server thread"]
	at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:26) ~[?:?]
	at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[?:?]
	at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[?:?]
	at com.jamesdpeters.minecraft.chests.menus.TextInputUI.getInput(TextInputUI.java:16) ~[?:?]
	at com.jamesdpeters.minecraft.chests.menus.PartyMenu.create(PartyMenu.java:139) ~[?:?]
	at com.jamesdpeters.minecraft.chests.menus.PartyMenu.lambda$updateIcons$1(PartyMenu.java:71) ~[?:?]
	at com.jamesdpeters.minecraft.chests.ClickableItem.run(ClickableItem.java:135) ~[?:?]
	at com.jamesdpeters.minecraft.chests.InventoryManager$InvListener.lambda$onInventoryClick$2(InventoryManager.java:174) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at com.jamesdpeters.minecraft.chests.InventoryManager$InvListener.onInventoryClick(InventoryManager.java:174) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2462) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1146) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3485-Spigot-b6d12d1-2ac7fa7]
	... 3 more

**Comment by cwatsonc** [comment]
I am seeing something similar on 1.19.2 but haven't seen the server logs yet -- I am just a consumer of this particular host -- also there's an error present when the mod is loaded (unsupported version) followed by the message "loaded successfully"... I'll get the server logs and add them to this thread.

**Comment by cwatsonc** [comment]
Seems like the above issue is related to maven-shade-plugin version numbers as mentioned in this issue in AnvilGUI repo https://github.com/WesJD/AnvilGUI/issues/147
