### ISSUE TITLE
warn spam in console

### ISSUE THREAD

**Issue by kiwols900** [ChestsPlusPlus/ChestsPlusPlus#87]
! [Sat 22:21:42 WARN  ChestsPlusPlus] Task #13171738 for ChestsPlusPlus v2.7-Release generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_17_R1/CraftWorld
    at ChestsPlusPlus-2.7-Release.jar//com.jamesdpeters.minecraft.chests.v1_17_R1.Crafting.craft(Crafting.java:27)
    at ChestsPlusPlus-2.7-Release.jar//com.jamesdpeters.minecraft.chests.crafting.Crafting.craft(Crafting.java:40)
    at ChestsPlusPlus-2.7-Release.jar//com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder.craftItem(VirtualCraftingHolder.java:386)
    at ChestsPlusPlus-2.7-Release.jar//com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder.craftItem(VirtualCraftingHolder.java:268)
    at ChestsPlusPlus-2.7-Release.jar//com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder$CraftItems.run(VirtualCraftingHolder.java:231)
    at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473)
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_17_R1.CraftWorld
    ... 13 more

**Comment by ceze88** [comment]
1.19.3 isnot supported in your version. You can get a dev build for 1.19.3 in our discord server.
