### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vampiregoat699** [ChestsPlusPlus/ChestsPlusPlus#96]
I follow the video and add the sign making it [ChestLink] [Farm] and it will add it to one chest but if I put the same sign on another chest it gives and error of invalid chest link for some reason. I can't even figure out how to get the sorter to work because putting the item frames on the hoppers with the item on it does nothing it just sends all items to a random chest and not the chest with the item on the frame.

**Comment by BallisticOK** [comment]
i have the same problem did you ever find a fix for this

**Comment by RHX0R3** [comment]
```
[01.12 03:49:00.892] INFORMATION: [Freebuild-1] [03:49:00 WARN]: [ChestsPlusPlus] Task #7573796 for ChestsPlusPlus v2.13-Release generated an exception
[01.12 03:49:00.896] INFORMATION: [Freebuild-1] java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R1/CraftWorld
[01.12 03:49:00.896] INFORMATION: [Freebuild-1]         at ChestsPlusPlus-2.13-Release-1733019369661.jar/com.jamesdpeters.minecraft.chests.v1_20_R1.Crafting.craft(Crafting.java:28) ~[ChestsPlusPlus-2.13-Release-1733019369661.jar:?]
[01.12 03:49:00.897] INFORMATION: [Freebuild-1]         at ChestsPlusPlus-2.13-Release-1733019369661.jar/com.jamesdpeters.minecraft.chests.crafting.Crafting.craft(Crafting.java:40) ~[ChestsPlusPlus-2.13-Release-1733019369661.jar:?]
[01.12 03:49:00.897] INFORMATION: [Freebuild-1]         at ChestsPlusPlus-2.13-Release-1733019369661.jar/com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder.craftItem(VirtualCraftingHolder.java:386) ~[ChestsPlusPlus-2.13-Release-1733019369661.jar:?]
[01.12 03:49:00.897] INFORMATION: [Freebuild-1]         at ChestsPlusPlus-2.13-Release-1733019369661.jar/com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder.craftItem(VirtualCraftingHolder.java:268) ~[ChestsPlusPlus-2.13-Release-1733019369661.jar:?]
[01.12 03:49:00.897] INFORMATION: [Freebuild-1]         at ChestsPlusPlus-2.13-Release-1733019369661.jar/com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder$CraftItems.run(VirtualCraftingHolder.java:231) ~[ChestsPlusPlus-2.13-Release-1733019369661.jar:?]
[01.12 03:49:00.898] INFORMATION: [Freebuild-1]         at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
[01.12 03:49:00.898] INFORMATION: [Freebuild-1]         at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
[01.12 03:49:00.898] INFORMATION: [Freebuild-1]         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
[01.12 03:49:00.898] INFORMATION: [Freebuild-1]         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
[01.12 03:49:00.899] INFORMATION: [Freebuild-1]         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
[01.12 03:49:00.899] INFORMATION: [Freebuild-1]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
[01.12 03:49:00.899] INFORMATION: [Freebuild-1]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
[01.12 03:49:00.900] INFORMATION: [Freebuild-1]         at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01.12 03:49:00.900] INFORMATION: [Freebuild-1] Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R1.CraftWorld
[01.12 03:49:00.900] INFORMATION: [Freebuild-1]         ... 13 more
```
